version: "3"
services:
  web:
    build:
      dockerfile: "Dockerfile.dev"
      context: "."
    restart: always
    ports:
      - ${PORT}:3001
    volumes:
      - ".:/home/app/app"
      - "$HOME/.cache:/home/app/.cache"
    environment:
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - HYALUS_CONFIG=$HYALUS_CONFIG
  db:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - db:/data/db
volumes:
  db:
